[package]
name = "decimal"
version = "0.2.0"
authors = ["TotallyNotJakub <totallynotjakub@proton.me>"]
repository = "https://github.com/Phoenix-Protocol-Group/phoenix-contracts"
edition = "2021"
license = "GPL 3.0"

[dependencies]
