on: [pull_request]

name: Basic

jobs:

  build:
    name: Build binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.71.0
          target: wasm32-unknown-unknown
          override: true
      - name: Build
        run: make build

  test:
    needs: build
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.71.0
          target: wasm32-unknown-unknown
          override: true
      - name: Run tests
        run: make test

  lints:
    needs: build
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.71.0
          override: true
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Run lints
        run: make lints
