name: Release Artifacts
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching v*, i.e. 1.0, 20.15.10
      - "v[0-9]+.[0-9]+.[0-9]+-rc*" # Push events to matching v*, i.e. 1.0-rc1, 20.15.10-rc5

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.71.0
          target: wasm32-unknown-unknown
          override: true
      - name: Install soroban-cli
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --locked --version 0.9.4 soroban-cli
      - name: Build artifacts
        run: make build
      - name: Generate checksums
        run: |
          cd target/wasm32-unknown-unknown/release/
          sha256sum *.wasm > checksums.txt
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.JAKUB_SECRET_CI }}
        run: >-
          gh release create ${{ github.ref_name }}
          target/wasm32-unknown-unknown/release/*.wasm
          target/wasm32-unknown-unknown/release/checksums.txt
          --generate-notes
          --title "${{ github.ref_name }}"

